apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: stud-reg-system
type: Opaque
stringData:
  DB_HOST: postgres.stud-reg-db.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: student_registration_system
  JWT_SECRET: ${JWT_SECRET}
  CORS_ORIGIN: https://${APP_DOMAIN}
