apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: stud-reg-system
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  sessionAffinity: None
