apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: stud-reg-db
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ${DB_PASSWORD}
  DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@postgres:5432/student_registration_system
